bien-studio/config/routes.rb
Rails.application.routes.draw do
  
  #NOTES
  get 'notes/annualretreat'
  get 'notes/croatiandesign'
  get 'notes/gamingcharity'
  get 'notes/newoffice'
  get 'notes/rimac'
  get 'notes/teded'
  
  
  #WORKS
  
  get 'works/altima'
  get 'works/beautypos'
  get 'works/flowxo'
  get 'works/novalty'
  get 'works/talentlyft'
  get 'works/testhero'
  get 'works/upbore'

  
  resources :works
  resources :homes
  resources :contacts
  resources :approaches
  resources :abouts
  resources :notes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bien-studio/app/models/about.rb
class About < ApplicationRecord
end

bien-studio/app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update, :destroy]

  # GET /abouts
  # GET /abouts.json
  def index
    @abouts = About.all
  end

  # GET /abouts/1
  # GET /abouts/1.json
  def show
  end

  # GET /abouts/new
  def new
    @about = About.new
  end

  # GET /abouts/1/edit
  def edit
  end

  # POST /abouts
  # POST /abouts.json
  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abouts/1
  # PATCH/PUT /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.json
  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def about_params
      params.fetch(:about, {})
    end
end

bien-studio/app/helpers/abouts_helper.rb
module AboutsHelper
end

bien-studio/app/views/abouts/_form.html.erb
<%= form_for(about) do |f| %>
  <% if about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
      <% about.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bien-studio/app/views/abouts/edit.html.erb
<h1>Editing About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Show', @about %> |
<%= link_to 'Back', abouts_path %>

bien-studio/app/views/abouts/index.html.erb
<div class = "whole">
    
    <div class = "top-header">
      <h1><u>Bien</u> is a studio for design, growth and good ideas.</h1>
    </div>
    
    <div class = "mid-pic">
        <img id = "mid-pic" src = "https://bien.studio/wp-content/uploads/2020/11/studio-left.jpg">
        <img id = "mid-pic2" src = "https://bien.studio/wp-content/uploads/2020/11/studio-right.jpg">
    </div>
    
    <div class = "values">
        <div class = "values-header">
            <p>Our values</p>
        </div>
        <div class = "values-text">
            <h1>We don’t shy away from challenges.</h1>
            <h1>Honesty and hard work spark great results.</h1>
            <h1>We’re motivated by goals, not trends.</h1>
            <h1>We like leaving and coming to work happy.</h1>
            <h1>Emails are important, but food is essential.</h1>
        </div>
        
    </div>
    
    
    <div class = "clients">
        <p>Selected clients</p>
        <img id = "client-logo" src = "https://cdn.freebiesupply.com/logos/large/2x/ted-2-logo-black-and-white.png">
        <img id = "client-logo2" src = "https://99designs-blog.imgix.net/blog/wp-content/uploads/2020/12/1200px-Feeding_America_logo.svg.png?auto=format&q=60&fit=max&w=930">
        <img id = "client-logo3" src = "https://www.tailorbrands.com/wp-content/uploads/2019/09/Flora.png">
        <img id = "client-logo4" src = "https://www.tailorbrands.com/wp-content/uploads/2020/03/Tailor-brands-White-transparent.png">
        <img id = "client-logo5" src = "https://lh5.googleusercontent.com/C-RjlDlxmdtKOvHXBiWK6X9MLucaC-a3vjrGkjySWeOtIaIR-48yVNJfCltsxjaUVlEZOaK4zJGw3tKHUBZEQShW2elqHV0i2JS7VPJmW2sxtqh338gr6395LsbyuZ4x-7R0MydR">
        <img id = "client-logo6" src = "https://www.tailorbrands.com/wp-content/uploads/2020/12/NY-Title-Eng-.png">
    </div>
    
    
    
    
    
    
    
    
    
    
    <div class = "team">
        <div class = "team-index">
            <h1 id = "team-header">Our team</h1>
            <div class = "team-card">
                <img alt="Card Back" src = "https://bien.studio/wp-content/uploads/2020/11/anja-new.jpg">
                <img class="img-top" alt="Card Front" src = "https://bien.studio/wp-content/uploads/2020/11/anja-alternate-768x940.jpg">
                <div class = "card-text">
                    <h1>Anja Grgić</h1>
                    <p>Project Manager</p>
                    <h2>anja@bien.studio</h2>
                </div>
            </div>
            <div class = "team-card">
                <img alt="Card Back" src = "https://bien.studio/wp-content/uploads/2020/11/ivan-bjelajac.jpg">
                <img class="img-top" alt="Card Front" src = "https://bien.studio/wp-content/uploads/2020/11/ivan-alternate.jpg">
                <div class = "card-text">
                    <h1>Ivan Bjelajac</h1>
                    <p>Co-Founder, Designer</p>
                    <h2>ivan@bien.studio</h2>
                </div>
            </div> 
            <div class = "team-card">
                <img alt="Card Back" src = "https://bien.studio/wp-content/uploads/2020/11/matija-jandric.jpg">
                <img class="img-top" alt="Card Front" src = "https://bien.studio/wp-content/uploads/2020/11/matija-alternate.jpg">
                <div class = "card-text">
                    <h1>Matija Jandrić</h1>
                    <p>Designer</p>
                    <h2>tija@bien.studio</h2>
                </div>
            </div>
            <div class = "team-card">
                <img alt="Card Back" src = "https://bien.studio/wp-content/uploads/2020/11/luka-marcec.jpg">
                <img class="img-top" alt="Card Front" src = "https://bien.studio/wp-content/uploads/2020/11/luka-alternate.jpg">
                <div class = "card-text">
                    <h1>Luka Marčec</h1>
                    <p>Designer</p>
                    <h2>luka.marcec@bien.studio</h2>
                </div>
            </div>
            <div class = "team-card">
                <img alt="Card Back" src = "https://bien.studio/wp-content/uploads/2020/11/luka-peric.jpg">
                <img class="img-top" alt="Card Front" src = "https://bien.studio/wp-content/uploads/2020/11/luka-p-alternate.jpg">
                <div class = "card-text">
                    <h1>Luka Perić</h1>
                    <p>Co-Founder</p>
                    <h2>luka@bien.studio</h2>
                </div>
            </div>
            <div class = "team-card">
                <img alt="Card Back" src = "https://bien.studio/wp-content/uploads/2020/11/mihael-miklosic.jpg">
                <img class="img-top" alt="Card Front" src = "https://bien.studio/wp-content/uploads/2020/11/mihael-alternate.jpg">
                <div class = "card-text">
                    <h1>Mihael Miklošić</h1>
                    <p>Designer</p>
                    <h2>mihael@bien.studio</h2>
                </div>
            </div>
            <div class = "team-card">
                <img alt="Card Back" src = "https://bien.studio/wp-content/uploads/2020/11/silvia-marincic.jpg">
                <img class="img-top" alt="Card Front" src = "https://bien.studio/wp-content/uploads/2020/11/silvia-alternate.jpg">
                <div class = "card-text">
                    <h1>Silvia Marinčić</h1>
                    <p>Designer</p>
                    <h2>silvia@bien.studio</h2>
                </div>
            </div>
        </div>
    </div>
    
</div>



<div class = "work-togethers">
    <div class = "content">
        <h1 id = "header" >Let's work together</h1>
        <div class = "email">
            <h2>Business inquiries / Contact</h2>
            <a target = "_blank" href = "mailto: hello@bien.studio">hello@bien.studio</a>
        </div>
        <div class = "social-media">
            <h2>Follow us on</h2>
            <a target = "_blank" href = "https://www.instagram.com/studiobien/">Instagram 
            </a>
        </div>
        <div class = "social-media">
            <h2>Keep up with stuff on</h2>
            <a target = "_blank" href = "https://m.facebook.com/Bien.design.studio/">Facebook 
            </a>
        </div>
        <div class = "social-media">
            <h2>Check out our work on</h2>
            <a target = "_blank" href = "https://dribbble.com/bien">Dribbble
            </a>
        </div>
        <div class = "social-media">
            <h2>Office address</h2>
            <a target = "_blank" href = "https://www.google.com/maps/place/Bien/@45.8043327,15.9905167,16z/data=!4m5!3m4!1s0x4765d79ba4b63ebd:0xe18abf733af11b5f!8m2!3d45.8081754!4d15.9847865?shorturl=1">Kneza Mislava 4, Zagreb, Croatia
            </a>
            </div>
    </div>
</div>

bien-studio/app/views/abouts/new.html.erb
<h1>New About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Back', abouts_path %>

bien-studio/app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_about_path(@about) %> |
<%= link_to 'Back', abouts_path %>