bien-studio/config/routes.rb
Rails.application.routes.draw do
  
  #NOTES
  get 'notes/annualretreat'
  get 'notes/croatiandesign'
  get 'notes/gamingcharity'
  get 'notes/newoffice'
  get 'notes/rimac'
  get 'notes/teded'
  
  
  #WORKS
  
  get 'works/altima'
  get 'works/beautypos'
  get 'works/flowxo'
  get 'works/novalty'
  get 'works/talentlyft'
  get 'works/testhero'
  get 'works/upbore'

  
  resources :works
  resources :homes
  resources :contacts
  resources :approaches
  resources :abouts
  resources :notes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bien-studio/app/models/approach.rb
class Approach < ApplicationRecord
end

bien-studio/app/controllers/approaches_controller.rb
class ApproachesController < ApplicationController
  before_action :set_approach, only: [:show, :edit, :update, :destroy]

  # GET /approaches
  # GET /approaches.json
  def index
    @approaches = Approach.all
  end

  # GET /approaches/1
  # GET /approaches/1.json
  def show
  end

  # GET /approaches/new
  def new
    @approach = Approach.new
  end

  # GET /approaches/1/edit
  def edit
  end

  # POST /approaches
  # POST /approaches.json
  def create
    @approach = Approach.new(approach_params)

    respond_to do |format|
      if @approach.save
        format.html { redirect_to @approach, notice: 'Approach was successfully created.' }
        format.json { render :show, status: :created, location: @approach }
      else
        format.html { render :new }
        format.json { render json: @approach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /approaches/1
  # PATCH/PUT /approaches/1.json
  def update
    respond_to do |format|
      if @approach.update(approach_params)
        format.html { redirect_to @approach, notice: 'Approach was successfully updated.' }
        format.json { render :show, status: :ok, location: @approach }
      else
        format.html { render :edit }
        format.json { render json: @approach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /approaches/1
  # DELETE /approaches/1.json
  def destroy
    @approach.destroy
    respond_to do |format|
      format.html { redirect_to approaches_url, notice: 'Approach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_approach
      @approach = Approach.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def approach_params
      params.fetch(:approach, {})
    end
end

bien-studio/app/helpers/approaches_helper.rb
module ApproachesHelper
end

bien-studio/app/views/approaches/_form.html.erb
<%= form_for(approach) do |f| %>
  <% if approach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(approach.errors.count, "error") %> prohibited this approach from being saved:</h2>

      <ul>
      <% approach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bien-studio/app/views/approaches/edit.html.erb
<h1>Editing Approach</h1>

<%= render 'form', approach: @approach %>

<%= link_to 'Show', @approach %> |
<%= link_to 'Back', approaches_path %>

bien-studio/app/views/approaches/index.html.erb
<p id="notice"><%= notice %></p>

<div class = "top">
  <h1>We design great products that have long lasting value.</h1>
  <p id = "top-p">In order to make the world a slightly better place.</p>
</div>

<div class = "mid-pic">
    <img src = "https://bien.studio/wp-content/uploads/2020/11/bien-team.jpg">
</div>

<div class = "mid-text">
    <h2>Bien is <u>7 people</u> that are</h2>
    <h3>Innovative</h3>
    <h3>Creative</h3>
    <h3>Passionate</h3>
</div>


<div class = "mid-pic-2">
    <img src = "https://bien.studio/wp-content/uploads/2020/11/animacija-bw.gif">
</div>

<div class = "mid-text-2">
    <div class = "top">
        <h2>We've helped teams with</h2>
    </div>
    <div class = "bottom">
        <div class = "point">
            <h3>Improving existing products</h3>
            <h4>We worked with already established companies that need continuous and dedicated work on existing features and redesigns of certain modules with legacy in mind.</h4>
        </div>
        <div class = "point">
            <h3>Launching startups</h3>
            <h4>We’ve branded and confirmed ideas through design loops before launching MVP’s. We’ve been able to help launch a number of startups from scratch.</h4>
        </div>
        <div class = "point">
            <h3>Product consulting</h3>
            <h4>We used our expertise in user experience to deliver unbiased reviews of digital products already on the market, along with those not yet launched.</h4>
        </div>
    </div>
    
</div>


<div class = "services">
    <div class = "services-header">
        <h1>Our services</h1>
    </div>
    <div class = "category">
        <h2>Brand</h2>
        <h1>Positioning</h1>
        <h1>Visual identity</h1>
        <h1>Guidelines</h1>
        <h1>Naming</h1>
        <h1>Animation</h1>
    </div>
    <div class = "category">
        <h2>Product design</h2>
        <h1>User experience design</h1>
        <h1>Design systems</h1>
        <h1>Prototyping</h1>
        <h1>Feature ideation</h1>
        <h1>User interface design</h1>
        <h1>Service design</h1>
    </div>
    <div class = "category">
        <h2>Strategy</h2>
        <h1>Design sprint workshops</h1>
        <h1>Product analysis</h1>
        <h1>User stories</h1>
    </div>
    <div class = "category">
        <h2>Engineering</h2>
        <h1>Web development</h1>
        <h1>Quality assurance</h1>
        <h1>CMS integration</h1>
    </div>
    <div class = "category">
        <h2>Other skills</h2>
        <h1>Exotic cuisine tasting</h1>
        <h1>Car customisation</h1>
        <h1>Kite flying</h1>
        <h1>Bike restoration</h1>
        <h1>Juggling</h1>
        <h1>Dog walking</h1>
    </div>
</div>









<div class = "work-togethers">
    <div class = "content">
        <h1 id = "header" >Let's work together</h1>
        <div class = "email">
            <h2>Business inquiries / Contact</h2>
            <a target = "_blank" href = "mailto: hello@bien.studio">hello@bien.studio</a>
        </div>
        <div class = "social-media">
            <h2>Follow us on</h2>
            <a target = "_blank" href = "https://www.instagram.com/studiobien/">Instagram 
            </a>
        </div>
        <div class = "social-media">
            <h2>Keep up with stuff on</h2>
            <a target = "_blank" href = "https://m.facebook.com/Bien.design.studio/">Facebook 
            </a>
        </div>
        <div class = "social-media">
            <h2>Check out our work on</h2>
            <a target = "_blank" href = "https://dribbble.com/bien">Dribbble
            </a>
        </div>
        <div class = "social-media">
            <h2>Office address</h2>
            <a target = "_blank" href = "https://www.google.com/maps/place/Bien/@45.8043327,15.9905167,16z/data=!4m5!3m4!1s0x4765d79ba4b63ebd:0xe18abf733af11b5f!8m2!3d45.8081754!4d15.9847865?shorturl=1">Kneza Mislava 4, Zagreb, Croatia
            </a>
            </div>
    </div>
</div>

bien-studio/app/views/approaches/new.html.erb
<h1>New Approach</h1>

<%= render 'form', approach: @approach %>

<%= link_to 'Back', approaches_path %>

bien-studio/app/views/approaches/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_approach_path(@approach) %> |
<%= link_to 'Back', approaches_path %>