bien-studio/config/routes.rb
Rails.application.routes.draw do
  
  #NOTES
  get 'notes/annualretreat'
  get 'notes/croatiandesign'
  get 'notes/gamingcharity'
  get 'notes/newoffice'
  get 'notes/rimac'
  get 'notes/teded'
  
  
  #WORKS
  
  get 'works/altima'
  get 'works/beautypos'
  get 'works/flowxo'
  get 'works/novalty'
  get 'works/talentlyft'
  get 'works/testhero'
  get 'works/upbore'

  
  resources :works
  resources :homes
  resources :contacts
  resources :approaches
  resources :abouts
  resources :notes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bien-studio/app/models/contact.rb
class Contact < ApplicationRecord
end

bien-studio/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.fetch(:contact, {})
    end
end

bien-studio/app/helpers/contacts_helper.rb
module ContactsHelper
end

bien-studio/app/views/contacts/_form.html.erb
<%= form_for(contact) do |f| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bien-studio/app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

bien-studio/app/views/contacts/index.html.erb
<head>
  
<script>
  function updateClock() {
    var currentTime = new Date();
    // Operating System Clock Hours for 12h clock
    var currentHoursAP = currentTime.getHours();
    // Operating System Clock Hours for 24h clock
    var currentHours = currentTime.getHours();
    // Operating System Clock Minutes
    var currentMinutes = currentTime.getMinutes();
    // Operating System Clock Seconds
    var currentSeconds = currentTime.getSeconds();
    // Adding 0 if Minutes & Seconds is More or Less than 10
    currentMinutes = (currentMinutes < 10 ? "0" : "") + currentMinutes;
    currentSeconds = (currentSeconds < 10 ? "0" : "") + currentSeconds;
    // Picking "AM" or "PM" 12h clock if time is more or less than 12
    var timeOfDay = (currentHours < 12) ? "AM" : "PM";
    // transform clock to 12h version if needed
    currentHoursAP = (currentHours > 12) ? currentHours - 12 : currentHours;
    // transform clock to 12h version after mid night
    currentHoursAP = (currentHoursAP == 0) ? 12 : currentHoursAP;
    // display first 24h clock and after line break 12h version
    var currentTimeString = currentHours + ":" + currentMinutes + ":" + currentSeconds + "";
    // print clock js in div #clock.
    $("#clock").html(currentTimeString);}
    $(document).ready(function () {
    setInterval(updateClock, 1000);
});
</script>

</head>




<p id="notice"><%= notice %></p>

<div class = "contact-main">
  <div class = "contact-header">
    <h1>We should work together.</h1>
  </div>
  <div class = "contact-middle">
    <h3>Business inquiries / Contact</h3>
    <h2>hello@bien.studio</h2>
  </div>    
  <div class = "contact-clock">
    <h3>Kneza Mislava 4, Zagreb, Croatia</h3>
    <div id="clock"></div>
  </div>
  <div class = "contact-social">
    <div class = "contact-card">
      <h1>Follow us on</h1>
      <a href = "https://www.instagram.com/studiobien/"><h2>Instagram</h2></a>
    </div>
    <div class = "contact-card">
      <h1>We also (rarely) post on</h1>
      <a href = "https://m.facebook.com/Bien.design.studio/"><h2>FaceBook</h2></a>
    </div>
    <div class = "contact-card">
      <h1>See our work</h1>
      <a href = "https://dribbble.com/bien"><h2>Dribbble</h2></a>
    </div>

  </div>

</div>

bien-studio/app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

bien-studio/app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>